### ISSUE TITLE
unreasonable plural forms for non-English interface translations 

### ISSUE THREAD

**Issue by shun2wang** [jamovi/jamovi-i18n#10]
Hi @jonathon-love 
In the comment at this PR[#6] I once mentioned about the plural form would be checked. I thought it was working well until just now when I was reviewing.

I've noticed that when multiple rows are selected, it seems that plurals are not displayed correctly in Chinese(also in Japanese), such as the "Delete rows" command. Let me guess the expected behavior：

- The below translation string in zh-cn.po file at [here](https://github.com/jamovi/jamovi-i18n/blob/33703c90eca52475ec55f26990d28f9b5c11944e/src/zh-cn.po#L500-L503) 
- for singular form，when i select a row，it should be `Delete row {row name}`，and `删除行{row name}` in Chinese
- for plural form,when I select multiple rows(e.g. 5 rows),it should be `Delete {5} rows`,and `删除 5 行` in Chinese. but now
it is `删除行s`. show as the pic below:
![jamovi-row-translation](https://user-images.githubusercontent.com/10348402/150293500-8f0ee055-bdc5-498b-9a3f-bca9a63ae32e.png)

As you know, Chinese nouns do not have plural forms, and they are not simply added with the 's' affix，Maybe the same for other non-Western characters.So I think it's an interface display mechanism issue, not a translation issue, do you think so?

Cheers

**Comment by jonathon-love** [comment]
ah! thanks @icekylin !

we'll take a look.
