### ISSUE TITLE
Some translations that may be missing

### ISSUE THREAD

**Issue by icekylin** [jamovi/jamovi-i18n#7]
Hi,
I found some strings when I am reviewing the translation file, that may not be defined:

1. 'pin level' [at](https://github.com/jamovi/jamovi/blob/68f080c4cc34158d9f1f2c1668225b2bd320984c/client/main/vareditor/datavarlevelwidget.js#L19)
2. 'Hide filter columns' [at](https://github.com/jamovi/jamovi/blob/68f080c4cc34158d9f1f2c1668225b2bd320984c/client/main/vareditor/filterwidget.js#L71)
3. 'remove nested filter' [at](https://github.com/jamovi/jamovi/blob/68f080c4cc34158d9f1f2c1668225b2bd320984c/client/main/vareditor/filterwidget.js#L404)
4. 'Hide options' [at](https://github.com/jamovi/jamovi/blob/68f080c4cc34158d9f1f2c1668225b2bd320984c/client/analysisui.html#L13)
5. ‘% is in error’，cannot confirm its code line but a pic by screenshot [at](https://postimg.cc/fVxn1z0Q)
6. ‘Enter link' &'Save' in note editor [at](https://postimg.cc/CRHD58fP)
7. 'This data set is no longer available' &'Close' in message at [here](https://github.com/jamovi/jamovi/blob/c8d7615ebca024562090c0c8ea6fae1c4e1ceb9c/server/jamovi/server/server.py#L253) & [here](https://github.com/jamovi/jamovi/blob/ea1e8276d25581079d16a69a38f72ebed14ff089/client/main/infobox.js#L270)
8. 'Show in main menu' [at](https://github.com/jamovi/jamovi/blob/68f080c4cc34158d9f1f2c1668225b2bd320984c/client/main/ribbon/ribbonmenu.js#L208)
9. 'cannot read properties of undefined....', cannot confirm its code line but a pic by screenshot [at](https://postimg.cc/zyLjvChj)
10. ’Refresh‘，show with info box under connection lost...,maybe [at](https://github.com/jamovi/jamovi/blob/ea1e8276d25581079d16a69a38f72ebed14ff089/client/main/infobox.js#L273)
11. ‘Cancel’ in an append info box [at](https://github.com/jamovi/jamovi/blob/20d841c7c889d5b70ec97e4620cb2702039db643/client/main/store/pagemodules.js#L27)

If I find that a new string that not specified, I‘ll update it here.

**Comment by jonathon-love** [comment]
thanks! this is very helpful

**Comment by jonathon-love** [comment]
hi @icekylin ,

thanks for all your work here ... i'm impressed with how thoroughly you've dived into the code to find these missing translations. i've committed a fix, and because you did all the hard work finding these things, i'll placed you as the author of that commit. this way you'll show up on the github contributors page for the main jamovi repo.

cheers
